#!/bin/sh

if [ -f "/etc/looptab" ]
then
	# Read Configuration File (exclude Comment Lines)
	value=`cat /etc/looptab | grep -vE "^#"`
else
	# Error
	echo "ERROR: File /etc/looptab does NOT exist. Exiting."
        exit 9
fi

# Create /dev/loop Folder
if [ ! -d "/dev/loop" ]
then
    mkdir -p "/dev/loop"
fi

# Iterate over each Device
cat /etc/looptab | grep -vE "^#" | while IFS= read -r line;
do
    # Echo
    echo "Processing Line: $line"

    # Extract "Source" Device
    sourceDevice=`echo "$line" | cut -f1 -d'	'`

    # Extract "Loop" Device
    loopDevice=`echo "$line" | cut -f2 -d'	'`

    # Create Loop Device (OLD SCHOOL - NOT NEEDED ANYMORE)
    #mknod -m650 $loopDevice b 7 0

    # Ensure Correct Permissions (OLD SCHOOL - NOT NEEDED ANYMORE)
    #chown root:disk $loopDevice

    # Mount Source Device to Loop Device (OLD SCHOOL - NOT NEEDED ANYMORE TO SPECIFY LOOP DEVICE ITSELF)
    #losetup $loopDevice $sourceDevice

    # Mount Source Device to Loop Device (NEW METHOD - Use First Available Device)
    loopDeviceAuto=`losetup -f --show $sourceDevice`

    # Create Symlink in /dev/loop/ Subfolder
    ln -s $loopDeviceAuto $loopDevice

    # Wait a bit
    sleep 1
done

# Return OK Code
exit 0
