#!/bin/sh

# Print every Command being executed
set -x

# Where to save Files
if [ -d "/var/log" ]
then
   # Use /var/log for saving Data
   LOG_BASEFOLDER="/var/log"
elif [ -d "/run/initramfs" ]
then
   # Use /run/initramfs for saving Data
   LOG_BASEFOLDER="/run/initramfs"
fi

# IOStat Debugging
IOSTAT_INTERVAL="1"
IOSTAT_COUNT=500

# Netcat Debugging
NC_BIN="/usr/bin/nc-full"
NC_HOST="192.168.3.66"
NC_PORT="12345"
NC_OPTIONS="-N -n -v ${NC_HOST} ${NC_PORT}"

# Check if Command Exists
# If not, default to "nc"
if [ ! -x "${NC_BIN}" ]
then
    # Echo
    echo "WARNING: the specified nc Binary ${NC_BIN} could NOT be found and/or is NOT executable."

    if [ -x "/usr/bin/nc" ]
    then
       NC_BIN="/usr/bin/nc"
    elif [ -x "/usr/sbin/nc" ]
    then
       NC_BIN="/usr/sbin/nc"
    else
       # Echo
       echo "WARNING: nc Binary couldn't be automatically Detected. Defaulting to <nc>"

       # Default Value
       NC_BIN="nc"
    fi
fi

# Echo
echo "Saving Logs to LOG_BASEFOLDER = ${LOG_BASEFOLDER}"  | ${NC_BIN} ${NC_OPTIONS}

# Define "losetup" Executable Path
LOSETUP_BIN="/usr/sbin/losetup-full"                                                  # Production (IMPORTANT: on the Real System it is /usr/sbin/losetup, in the initramfs it is /usr/bin/losetup !!!) - "losetup" also works correctly though
#LOSETUP_BIN="/usr/src/initramfs-investigation/6.8.0-40-generic/main/usr/bin/losetup" # Testing with uncompressed initramfs

# Define "losetup" Command-Line Options
LOSETUP_OPTIONS="-b 4096"

# Timestamp
TIMESTAMP=`date +"%Y%m%d-%H%M%S"`

# Custom Function
send_iostat_to_netcat() {
    # Initialize counter
    local netcatLoopCounter=0

    # Initialize Variable
    local currentTimestamp=""

    while [ $netcatLoopCounter -lt ${IOSTAT_COUNT} ]
    do
        # Current Time
        currentTimestamp=`date +"%Y%m%d_%H%M%S"`

        # Echo
        echo "Start Sending ${LOG_BASEFOLDER}/iostat.debug.$TIMESTAMP at Datetime = $currentTimestamp"  | ${NC_BIN} ${NC_OPTIONS}
        echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

        # Send Data
        cat ${LOG_BASEFOLDER}/iostat.debug.$TIMESTAMP | ${NC_BIN} ${NC_OPTIONS}

        # Echo
        echo "Finished Sending ${LOG_BASEFOLDER}/iostat.debug.$TIMESTAMP at Datetime = $currentTimestamp"  | ${NC_BIN} ${NC_OPTIONS}
        echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

        # Wait
        sleep ${IOSTAT_INTERVAL}

        # Increase Counter
        netcatLoopCounter=$((netcatLoopCounter+1))
    done

    # Exit Gracefully
    return 0
}

# Echo
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
echo "Starting DEBUG at $TIMESTAMP"  | ${NC_BIN} ${NC_OPTIONS}

# Check if Command Exists
# If not, default to "losetup"
if [ ! -x "${LOSETUP_BIN}" ]
then
    # Echo
    echo "WARNING: the specified losetup Binary ${LOSETUP_BIN} could NOT be found and/or is NOT executable." | ${NC_BIN} ${NC_OPTIONS}

    if [ -x "/usr/bin/losetup" ]
    then
       LOSETUP_BIN="/usr/bin/losetup"
    elif [ -x "/usr/sbin/losetup" ]
    then
       LOSETUP_BIN="/usr/sbin/losetup"
    else
       # Echo
       echo "WARNING: losetup Binary couldn't be automatically Detected. Defaulting to <losetup>" | ${NC_BIN} ${NC_OPTIONS}

       # Default Value
       LOSETUP_BIN="losetup"
    fi
fi

# Echo
echo "INFO: Using losetup Executable / Command: ${LOSETUP_BIN}" | ${NC_BIN} ${NC_OPTIONS}

# List /dev/mapper/ Devices
echo "List of /dev/mapper/ Devices" | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
ls -l /dev/mapper/* | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

# List /dev/loop/ Devices
echo "List of /dev/loop/ Devices" | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
ls -l /dev/loop/* | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

# Get Output of zpool status -v
echo "Get zpool status Output" | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
zpool status -v | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

# Get Output of zfs version
echo "Get zfs version Output" | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
zfs version | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

# Get Kernel Version
echo "Get Kernel version Output" | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
uname -a | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

# Get Output of zdb -C
echo "Get zdb -C Output" | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
zdb -C | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

# Get Outout of zpool get path rpool all-vdevs
echo "Get zpool get path rpool all-vdevs Output" | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
zpool get path rpool all-vdevs | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

# Get Outout of zpool get all rpool
echo "Get zpool get all rpool Output" | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
zpool get all rpool | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

# Get Outout of zpool get all rpool all-vdevs
echo "Get zpool get all rpool all-vdevs Output" | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
zpool get all rpool all-vdevs | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

# Iterate over each Device
echo "Analysing Loop Device Details" | ${NC_BIN} ${NC_OPTIONS}
loopDevicesList=""
luksDevicesList=""
physicalDevicesList=""

cat /etc/looptab | grep -vE "^#" | while IFS= read -r line;
do
    # Extract "ID"
    loopDeviceNumber=`echo "$line" | cut -f1 -d'	'`

    # Extract "Source" Device (full Path)
    sourceDevice=`echo "$line" | cut -f2 -d'	'`

    # Extract "Loop" Device with Custom Name (full Path)
    loopDeviceCustomName=`echo "$line" | cut -f3 -d'	'`

    # Build "Standardized" Device Path
    loopDevicePath="/dev/loop$loopDeviceNumber"

    # Check if Device Exists
    if [ -b $loopDevicePath ]
    then
        # Echo
        echo "Check Loop Device Information for $loopDevicePath"| ${NC_BIN} ${NC_OPTIONS}
        echo "Executing Command: ${LOSETUP_BIN} $loopDevicePath" | ${NC_BIN} ${NC_OPTIONS}
        echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

        # Run Command
        ${LOSETUP_BIN} --verbose $loopDevicePath --list --output NAME,SIZELIMIT,OFFSET,AUTOCLEAR,RO,BACK-FILE,DIO,LOG-SEC,BACK-INO,BACK-MAJ:MIN,MAJ:MIN,PARTSCAN | ${NC_BIN} ${NC_OPTIONS}

        echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

        # Add to List for iostat Processing later on
        loopDevicesList="${loopDevicesList} ${loopDeviceCustomName}"
        luksDevicesList="${luksDevicesList} ${sourceDevice}"

        # Determine the associated Physical Device
        physicalDeviceWithPartition=`lsblk -s -npo pkname ${sourceDevice} | head -n1`
        physicalDevice=`lsblk -npo pkname ${physicalDeviceWithPartition} | head -n1`
        physicalDevicesList="${physicalDevicesList} ${physicalDevice}"
    fi
done

# Get dmsetup table Output
echo "Analysing dmsetup Table Ouput" | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
dmsetup table | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

# Get lsblk Output
echo "Analysing lsblk Ouput" | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
lsblk --all --bytes -to +START,SIZE,TYPE --output NAME,ALIGNMENT,MIN-IO,OPT-IO,PHY-SEC,LOG-SEC,ROTA,SCHED,RQ-SIZE,RA,WSAME,START,SIZE,TYPE,MAJ:MIN | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

# Get a "one-off" iostat Output
echo "Analysing iostat Ouput (one-off)" | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
set -- ${physicalDevicesList} ${luksDevicesList} ${loopDevicesList}
iostat -dk -zyx $@ ${IOSTAT_INTERVAL} 1 | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

# Launch "iostat" in the Background and save to File
echo "Launching iostat in the Background and saving Results to ${LOG_BASEFOLDER}/iostat.debug.$TIMESTAMP"
touch ${LOG_BASEFOLDER}/iostat.debug.$TIMESTAMP
set -- ${physicalDevicesList} ${luksDevicesList} ${loopDevicesList}
iostat -dk -zyx $@ ${IOSTAT_INTERVAL} ${IOSTAT_COUNT} > ${LOG_BASEFOLDER}/iostat.debug.$TIMESTAMP &

# Then try to periodically send via Netcat
send_iostat_to_netcat &

# Force zpool reopen
# Disabled for testing on Real Booting System
#zpool reopen
#zpool reopen rpool

# Echo
echo "Ending DEBUG at $TIMESTAMP"  | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

# Send Contents of /run/initramfs/initramfs.debug to Remote Netcat Server
if [ -f "/run/initramfs/initramfs.debug" ]
then
   echo "Sending /run/initramfs/initramfs.debug to Remote Netcat Server" | ${NC_BIN} ${NC_OPTIONS}
   echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
   cat "/run/initramfs/initramfs.debug" | ${NC_BIN} ${NC_OPTIONS}
   echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
fi

# Copy /run/initramfs/initramfs.debug to /var/log/initramfs.debug.$TIMESTAMP
if [ -f "/run/initramfs/initramfs.debug" ]
then
   echo "Copying /run/initramfs/initramfs.debug to /var/log/initramfs.debug.$TIMESTAMP"
   cp "/run/initramfs/initramfs.debug" "/var/log/initramfs.debug.$TIMESTAMP"
fi

# Send Contents of dmesg to Remote Netcat Server
echo "Sending dmesg to Remote Netcat Server" | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}
dmesg | ${NC_BIN} ${NC_OPTIONS}
echo "============================================================================================================================================================" | ${NC_BIN} ${NC_OPTIONS}

# Dump dmesg to ${LOG_BASEFOLDER}/dmesg.debug.$TIMESTAMP
echo "Dumping dmesg to ${LOG_BASEFOLDER}/dmesg.debug.$TIMESTAMP"
dmesg > "${LOG_BASEFOLDER}/dmesg.debug.$TIMESTAMP" 2>&1

# Return OK Code
exit 0
