#!/bin/sh
# looptab hook script

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

# Begin real processing below this line

# Copy nc Executable
copy_exec "/usr/bin/nc" "/usr/bin/nc-full"

# Copy lsblk Executable
copy_exec "/usr/bin/lsblk"

# Copy zsb Executable
copy_exec "/usr/sbin/zdb"

# Copy looptab-debug Script
copy_exec "/usr/sbin/looptab-debug"

# Return OK
exit 0
