#!/bin/sh
# looptab hook script

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

# Begin real processing below this line

# Copy Netcat Executable
copy_exec "/usr/bin/nc"

# Return OK
exit 0
