#!/bin/sh
# looptab hook script

PREREQ="clevis udev"
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line

if [ ! -f "/etc/looptab" ]; then
     echo "ERROR: File /etc/looptab does NOT Exist. ABORTING ..."
     exit 0
fi

# Copy Configuration File
copy_file config "/etc/looptab"

# Copy looptab Binary
copy_exec "/usr/sbin/looptab"

# Copy the "full" losetup Binary
copy_exec "/usr/sbin/losetup" "/usr/sbin/losetup-full"

# Return OK
exit 0
