#!/bin/sh
# looptab hook script

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line

if [ ! -x "/etc/looptab" ]; then
     exit 0
fi

# Copy Configuration File
cp /etc/looptab "${DESTDIR}/etc"

# Copy Binary
cp /usr/local/sbin/looptab "${DESTDIR}/sbin"

# Return OK
exit 0
